"""Publication-ready production freeze (Part 7B1).

This is the THIRD freeze scope in the program, and the three must not be conflated:

* **Historical research freezes** — ``evaluator_freeze.json`` and
  ``challenger_implementation_freeze.json`` certify the experiment that selected
  Challenger B. Preserved byte-for-byte; verified at their own historical commits.
* **Part-6B production freeze** — ``production_freeze.json`` certifies the
  production state at the moment B became the default. It is now HISTORICAL:
  Part 7B1 deliberately changed export/schema files inside its closure. It is
  preserved byte-for-byte and is NOT regenerated.
* **This publication freeze** — certifies the CURRENT publication-ready state: the
  schema-1.4 export that states the ElectionNoise identity explicitly.

Reconstructibility rule, carried forward from Part 3D-R: every recorded entry must
have a non-null committed HEAD hash equal to its working-tree hash with no
uncommitted edit. :func:`build` refuses to emit an artifact otherwise.
"""

from __future__ import annotations

from datetime import datetime, timezone
import hashlib
import importlib
import json
from pathlib import Path
import subprocess
import sys

REPO_ROOT = Path(__file__).resolve().parents[3]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.prospective_archive.archive import ARCHIVE_SCHEMA_VERSION
from scripts.simulator.config import (
    ADOPTED_ELECTION_NOISE_CANDIDATE,
    BENCHMARK_LINEAGE_CANDIDATE,
    MODEL_VERSION,
    RELEASE_TAG,
)
from scripts.static_exporter.exporter import PUBLICATION_SCHEMA_VERSION
from scripts.vote_share_calibration.election_noise_b import LEGACY_MODEL_ID, MODEL_ID

HERE = Path(__file__).resolve().parent
OUT = HERE / "publication_freeze.json"
A2 = REPO_ROOT / "diagnostics/election_noise_v2/control_baseline_amendment2"
CH = REPO_ROOT / "diagnostics/election_noise_v2/challengers"
COMP = REPO_ROOT / "diagnostics/election_noise_v2/competition"

REFERENCES = {
    "adopt_b_decision_commit": "ff89621848c95ac9320804ffc4f148454f522284",
    "evaluator_refreeze_commit": "a5b8c7a234acf60cac71ef1ab1439343fae88639",
    "challenger_freeze_commit": "1450e6f301a98d5d6e4af1357113435534b0e7a9",
    "part6a_production_implementation_commit": "8c8eaed20292961c8c262d1568b73a9ff1ebd679",
    "part6b_production_default_commit": "50794c6b86b51fa602f8acad624e97befb7ac274",
    "part6b_production_freeze_commit": "8eadecc683b45acf914746bafe28ce6b9d0a8472",
    "part7a_data_refresh_commit": "ce78fcb4a67c974d325e3d5a93267b90ee5cc606",
    "part7a_forecast_commit": "3f87710e0d5dcd3e1a3d812c6f215ddefdcb320d",
}

#: Files defining which law runs and how the artifact describes it.
PUBLICATION_FILES_TRACKED = [
    "scripts/static_exporter/exporter.py",
    "scripts/prospective_archive/archive.py",
    "scripts/presentation_reexport/reexport.py",
    "scripts/simulator/config.py",
    "scripts/simulator/engine.py",
    "scripts/simulator/reproducibility.py",
    "scripts/vote_share_calibration/national_engine.py",
    "scripts/vote_share_calibration/election_noise_b.py",
    "scripts/publication_pipeline/pipeline.py",
]

TEST_FILES = [
    "tests/test_publication_metadata_namespace.py",
    "tests/test_production_default_is_b.py",
    "tests/test_static_exporter.py",
    "tests/test_prospective_archive.py",
]

#: Preserved byte-for-byte; never regenerated by this freeze.
PRESERVED = {
    "diagnostics/election_noise_v2/control_baseline_amendment2/evaluator_freeze.json":
        "3142f81c2494773448f2a48cbe57ccd964fa807891477155cc89e1c3b5f04bae",
    "diagnostics/election_noise_v2/challengers/challenger_implementation_freeze.json":
        "2454ac15309361443656fe1d00abd5cb655d5a8efc8ddaded9e8c7164d8c1c22",
    "diagnostics/election_noise_v2/competition/decision.json":
        "f0e534bb6f2a5c83dd32ae53a7dc916ed29ad85d1ea1910143f954b4689116bc",
    "diagnostics/election_noise_v2/production_promotion/production_freeze.json":
        "c3e1358c823dc2c1dd0eaf0352f6bae5d4f8e95ad66064374a0d19c6872f0115",
    "data/processed/prospective_forecasts/20260831T161556Z-e273ed69/snapshot.json": None,
}


class UncommittedPublicationState(RuntimeError):
    """Raised when the freeze would record content that is not committed."""


def sha256_file(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def _head_blob_sha256(rel: str) -> str | None:
    try:
        blob = subprocess.check_output(["git", "show", f"HEAD:{rel}"], cwd=REPO_ROOT,
                                       stderr=subprocess.DEVNULL)
    except subprocess.CalledProcessError:
        return None
    return hashlib.sha256(blob).hexdigest()


def _git(*a: str) -> str:
    return subprocess.check_output(["git", *a], cwd=REPO_ROOT).decode().strip()


def _record(rel: str) -> dict:
    p = REPO_ROOT / rel
    wt = sha256_file(p) if p.exists() else None
    head = _head_blob_sha256(rel)
    return {"working_tree_sha256": wt, "head_sha256": head,
            "uncommitted_local_edit": head is not None and head != wt}


def production_import_closure() -> dict:
    for mod in ("scripts.simulator.engine",
                "scripts.static_exporter.exporter",
                "scripts.prospective_archive.archive",
                "scripts.publication_pipeline.pipeline",
                "scripts.vote_share_calibration.election_noise_b"):
        importlib.import_module(mod)
    out: dict[str, dict] = {}
    for name, module in sorted(sys.modules.items()):
        f = getattr(module, "__file__", None)
        if not f:
            continue
        path = Path(f).resolve()
        try:
            rel = str(path.relative_to(REPO_ROOT))
        except ValueError:
            continue
        if not (rel.startswith("scripts/") or rel.startswith("diagnostics/")):
            continue
        rec = _record(rel)
        rec["module"] = name
        out[rel] = rec
    return out


def build(test_results: dict | None = None) -> dict:
    closure = production_import_closure()
    groups = {"publication_implementation": {r: _record(r) for r in PUBLICATION_FILES_TRACKED},
              "tests": {r: _record(r) for r in TEST_FILES}}
    bad = []
    for scope, table in list(groups.items()) + [("import_closure", closure)]:
        for rel, rec in table.items():
            if rec["head_sha256"] is None or rec["uncommitted_local_edit"]:
                bad.append(f"{scope}: {rel}")
    if bad:
        raise UncommittedPublicationState(
            "the publication freeze must record committed content only:\n"
            + "\n".join(f"  {b}" for b in bad))

    preserved = dict(PRESERVED)
    pred = "data/processed/prospective_forecasts/20260831T161556Z-e273ed69/snapshot.json"
    preserved[pred] = sha256_file(REPO_ROOT / pred)
    preserved_check = {rel: {"expected": exp, "actual": sha256_file(REPO_ROOT / rel),
                             "preserved": sha256_file(REPO_ROOT / rel) == exp}
                       for rel, exp in preserved.items()}

    cert_path = HERE / "publication_certification.json"
    cert = json.loads(cert_path.read_text())

    return {
        "artifact": "ELECTIONNOISE PUBLICATION-READY PRODUCTION FREEZE",
        "purpose": ("Certify the current publication-ready state: the schema-1.4 export that "
                    "states the ElectionNoise identity explicitly."),
        "scope_note": (
            "Does NOT supersede or regenerate the historical research freezes or the Part-6B "
            "production freeze. Those certify earlier states, are preserved byte-for-byte, and "
            "verify at their own commits."),
        "freeze_timestamp_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "git": {"implementation_commit": _git("rev-parse", "HEAD"),
                "branch": _git("rev-parse", "--abbrev-ref", "HEAD"),
                "worktree_clean_at_freeze": _git("status", "--porcelain") == ""},
        "references": REFERENCES,
        "model_identity": {
            "model_version": MODEL_VERSION,
            "release_tag": RELEASE_TAG,
            "release_status": "release candidate; not declared stable",
            "election_noise_law": MODEL_ID,
            "election_noise_candidate": ADOPTED_ELECTION_NOISE_CANDIDATE,
            "superseded_election_noise_law": LEGACY_MODEL_ID,
            "superseded_election_noise_candidate": "CONTROL",
            "benchmark_lineage_candidate": BENCHMARK_LINEAGE_CANDIDATE,
            "namespace_note": (
                "model.candidate is the botten-ada benchmark/model-lineage label and is NOT the "
                "ElectionNoise challenger. CONTROL is not ElectionNoise Challenger A."),
        },
        "schema": {"publication_schema_version": PUBLICATION_SCHEMA_VERSION,
                   "archive_schema_version": ARCHIVE_SCHEMA_VERSION,
                   "reexport_pinned_to": "1.3"},
        "successor_export": {
            "generation_id": cert["supersession"]["successor_generation"],
            "predecessor_generation": cert["supersession"]["predecessor_generation"],
            "deterministic_payload_sha256": cert["deterministic_payload_sha256"],
            "payload_hash_unchanged_vs_part7a": cert["payload_hash_unchanged_vs_part7a"],
            "export_file_sha256": cert["export_file_sha256"],
            "scientific_differences_vs_part7a": cert["scientific_equality_vs_part7a"]["scientific_differences"],
            "certification_artifact_sha256": sha256_file(cert_path),
            "website_published": False,
        },
        "preserved_artifacts": preserved_check,
        "publication_file_hashes": groups,
        "production_import_closure_hashes": closure,
        "targeted_test_results": test_results or {},
        "reconstructibility": {"every_entry_committed": True,
                               "working_tree_equals_head": True,
                               "no_uncommitted_local_edit": True},
    }


def verify(frozen: dict | None = None) -> dict:
    if frozen is None:
        frozen = json.loads(OUT.read_text())
    drift, checks = [], 0
    tables = [(f"publication:{g}", t) for g, t in frozen["publication_file_hashes"].items()]
    tables.append(("import_closure", frozen["production_import_closure_hashes"]))
    for group, table in tables:
        for rel, rec in table.items():
            checks += 1
            p = REPO_ROOT / rel
            actual = sha256_file(p) if p.exists() else None
            if actual != rec["working_tree_sha256"]:
                drift.append({"group": group, "file": rel,
                              "expected": rec["working_tree_sha256"], "actual": actual})
            elif rec["head_sha256"] is None or rec["uncommitted_local_edit"]:
                drift.append({"group": group, "file": rel,
                              "issue": "recorded entry is not committed content"})
    for rel, rec in frozen["preserved_artifacts"].items():
        checks += 1
        actual = sha256_file(REPO_ROOT / rel)
        if actual != rec["expected"]:
            drift.append({"group": "preserved_artifact", "file": rel,
                          "expected": rec["expected"], "actual": actual})
    return {"checks": checks, "drift": drift, "publication_unchanged": not drift}


def main() -> int:
    frozen = build()
    OUT.write_text(json.dumps(frozen, indent=2) + "\n")
    res = verify(frozen)
    print(f"publication freeze written; {res['checks']} hashes recorded")
    print("closure modules:", len(frozen["production_import_closure_hashes"]))
    print("publication_unchanged =", res["publication_unchanged"])
    for d in res["drift"]:
        print("  DRIFT:", d)
    print("successor generation:", frozen["successor_export"]["generation_id"])
    print("payload unchanged   :", frozen["successor_export"]["payload_hash_unchanged_vs_part7a"])
    return 0 if res["publication_unchanged"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
